defaults: &defaults
  morphology: stem_enru
  enable_star: true
  port: 9312

development:
  <<: *defaults

test:
  <<: *defaults
  port: 9313

production:
  <<: *defaults
  pid_file: /home/ajaxy/www/venturedb/shared/pids/searchd.pid
