defaults: &defaults
  morphology: stem_enru
  port: 9312

development:
  <<: *defaults

test:
  <<: *defaults
  port: 9313

production:
  <<: *defaults
  pid_file: /srv/venture.staging/shared/pids/searchd.pid
